# Generated by Django 4.1.5 on 2023-01-23 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import owners.models
import owners.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('tagline', models.CharField(blank=True, max_length=50, null=True)),
                ('national_ID', models.ImageField(upload_to=owners.models.user_directory_path, validators=[owners.validators.validate_file_size], verbose_name='National ID')),
                ('certificate_of_incorporation', models.ImageField(upload_to=owners.models.user_directory_path, validators=[owners.validators.validate_file_size], verbose_name='Certificate of Incorporation')),
                ('proof_of_residence', models.ImageField(upload_to=owners.models.user_directory_path, validators=[owners.validators.validate_file_size], verbose_name='Proof of Residence')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=owners.models.user_directory_path, validators=[owners.validators.validate_file_size], verbose_name='Logo')),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
