# Generated by Django 4.0.2 on 2023-03-14 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import owners.models
import owners.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('personal_phone_number', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=50)),
                ('business_name_slug', models.SlugField(blank=True, unique=True)),
                ('address', models.TextField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('whatsapp_number', models.CharField(max_length=50)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('national_ID', models.ImageField(blank=True, null=True, upload_to=owners.models.user_directory_path, validators=[owners.validators.validate_file_size], verbose_name='National ID')),
                ('certificate_of_incorporation', models.ImageField(blank=True, null=True, upload_to=owners.models.user_directory_path, validators=[owners.validators.validate_file_size], verbose_name='Certificate of Incorporation')),
                ('proof_of_residence', models.ImageField(blank=True, null=True, upload_to=owners.models.user_directory_path, validators=[owners.validators.validate_file_size], verbose_name='Proof of Residence')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=owners.models.user_directory_path, validators=[owners.validators.validate_file_size], verbose_name='Logo')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
