# Generated by Django 4.0.2 on 2023-02-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_carowner_completed_profile_carowner_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='completed_profile',
        ),
    ]
