# Generated by Django 4.0.2 on 2023-02-09 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0007_carcategory_remove_car_owner_and_more'),
        ('owners', '0003_remove_carowner_completed_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarOwner',
            new_name='Owner',
        ),
    ]
