# Generated by Django 4.0.2 on 2023-02-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_rename_carowner_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='owners.owner')),
                ('rating_number', models.PositiveIntegerField()),
            ],
        ),
    ]
