# Generated by Django 4.0.2 on 2023-03-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='verified',
        ),
        migrations.AddField(
            model_name='owner',
            name='whatsapp_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
