# Generated by Django 4.0.2 on 2023-03-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0006_remove_owner_tagline_remove_owner_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='business_name_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
