# Generated by Django 4.0.2 on 2023-03-12 21:18

from django.db import migrations, models
import owners.models
import owners.validators


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0007_owner_business_name_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='owner',
            name='certificate_of_incorporation',
            field=models.ImageField(blank=True, null=True, upload_to=owners.models.user_directory_path, validators=[owners.validators.validate_file_size], verbose_name='Certificate of Incorporation'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='national_ID',
            field=models.ImageField(blank=True, null=True, upload_to=owners.models.user_directory_path, validators=[owners.validators.validate_file_size], verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='proof_of_residence',
            field=models.ImageField(blank=True, null=True, upload_to=owners.models.user_directory_path, validators=[owners.validators.validate_file_size], verbose_name='Proof of Residence'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
