# Generated by Django 4.1.5 on 2023-01-23 15:06

import cars.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import owners.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('number_of_doors', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_day', models.PositiveIntegerField(default=0)),
                ('number_of_seats', models.PositiveIntegerField(default=1)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=9)),
                ('car_class', models.CharField(choices=[('Convertible', 'Convertible'), ('Standard', 'Standard'), ('Truck', 'Truck'), ('SUV', 'SUV'), ('Commuter_Omnibus', 'Commuter Omnibus'), ('Vans', 'Vans'), ('Luxury_Car', 'Luxury Car')], default='Standard', max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('car_image', models.ImageField(upload_to=cars.models.user_directory_path_cars, validators=[owners.validators.validate_file_size], verbose_name='Car Image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='owners.carowner')),
                ('pickup_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.location')),
            ],
        ),
    ]
