# Generated by Django 4.0.2 on 2023-02-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='booked',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
