# Generated by Django 4.0.2 on 2023-02-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_availability_car_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Disel', 'Disel')], default='Disel', max_length=6),
        ),
        migrations.AlterField(
            model_name='car',
            name='booked',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('Convertible', 'Convertible'), ('Standard', 'Standard'), ('Truck', 'Truck'), ('SUV', 'SUV'), ('Commuter Omnibus', 'Commuter Omnibus'), ('Vans', 'Vans'), ('Luxury Car', 'Luxury Car')], default='Standard', max_length=50),
        ),
    ]
