# Generated by Django 4.0.2 on 2023-02-03 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_fuel_alter_car_booked_alter_car_car_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
