# Generated by Django 4.0.2 on 2023-02-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pickup_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.location'),
        ),
    ]
