# Generated by Django 4.0.2 on 2023-02-09 10:23

import cars.models
from django.db import migrations, models
import owners.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_pickup_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('category_name', models.CharField(choices=[('Convertible', 'Convertible'), ('Standard', 'Standard'), ('Truck', 'Truck'), ('SUV', 'SUV'), ('Commuter Omnibus', 'Commuter Omnibus'), ('Vans', 'Vans'), ('Luxury Car', 'Luxury Car')], default='Standard', max_length=50)),
                ('price_per_day_min', models.PositiveIntegerField(default=0, verbose_name='Minimum price per day')),
                ('price_per_day_max', models.PositiveIntegerField(default=0, verbose_name='Maximum price per fay')),
                ('number_of_seats', models.PositiveIntegerField(default=1)),
                ('automatic', models.BooleanField(default=False)),
                ('manual', models.BooleanField(default=False)),
                ('mileage_limit', models.CharField(choices=[('Limited', 'Limited'), ('Unlimited', 'Unlimited')], default='Limited', max_length=9, verbose_name='Mileage/Kilometres limit')),
                ('mileage', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Mileage/Kilometres')),
                ('availability', models.BooleanField(default=True)),
                ('free_cancelation', models.BooleanField(default=True)),
                ('model_image', models.ImageField(upload_to=cars.models.user_directory_path_cars, validators=[owners.validators.validate_file_size], verbose_name='Model image')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pickup_location',
        ),
    ]
