# Generated by Django 4.0.2 on 2023-02-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_rename_carowner_owner'),
        ('cars', '0007_carcategory_remove_car_owner_and_more'),
        ('bookings', '0007_alter_booking_booked_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AddField(
            model_name='carcategory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='owners.owner'),
        ),
        migrations.AddField(
            model_name='carcategory',
            name='pickup_location',
            field=models.ManyToManyField(to='cars.Location'),
        ),
    ]
