# Generated by Django 4.0.2 on 2023-02-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_rename_category_name_carcategory_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcategory',
            name='automatic',
        ),
        migrations.RemoveField(
            model_name='carcategory',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='carcategory',
            name='manual',
        ),
        migrations.AddField(
            model_name='carcategory',
            name='inventory_available',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AddField(
            model_name='carcategory',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Both', 'Both')], default='Automatic', max_length=9, verbose_name='Type of transmission'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='free_cancelation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
    ]
