# Generated by Django 4.0.2 on 2023-02-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_carcategory_automatic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcategory',
            old_name='free_cancelation',
            new_name='free_cancellation',
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='price_per_day_max',
            field=models.PositiveIntegerField(default=0, verbose_name='Maximum price per day'),
        ),
    ]
