# Generated by Django 4.0.2 on 2023-02-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_rename_free_cancelation_carcategory_free_cancellation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcategory',
            name='large_bags',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carcategory',
            name='small_bags',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
