# Generated by Django 4.0.2 on 2023-02-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_carcategory_large_bags_carcategory_small_bags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcategory',
            name='pickup_location',
            field=models.ManyToManyField(to='cars.Location', verbose_name='Available pick-up locations'),
        ),
    ]
