# Generated by Django 4.0.2 on 2023-02-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_carcategory_pickup_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcategory',
            name='price_per_day_max',
        ),
        migrations.RemoveField(
            model_name='carcategory',
            name='price_per_day_min',
        ),
        migrations.AddField(
            model_name='carcategory',
            name='price_per_day',
            field=models.PositiveIntegerField(default=0, verbose_name='Price per day'),
        ),
    ]
