# Generated by Django 4.0.2 on 2023-03-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_remove_carcategory_price_per_day_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcategory',
            old_name='large_bags',
            new_name='bags',
        ),
        migrations.RenameField(
            model_name='carcategory',
            old_name='small_bags',
            new_name='doors',
        ),
        migrations.RemoveField(
            model_name='carcategory',
            name='free_cancellation',
        ),
        migrations.AddField(
            model_name='carcategory',
            name='min_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carcategory',
            name='ratings',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carcategory',
            name='security_deposit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
