# Generated by Django 4.0.2 on 2023-03-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_rename_large_bags_carcategory_bags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcategory',
            name='model_name_slug',
            field=models.SlugField(blank=True),
        ),
    ]
