# Generated by Django 4.0.2 on 2023-03-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_carcategory_model_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcategory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
