# Generated by Django 4.0.2 on 2023-03-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_carcategory_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carcategory',
            options={'ordering': ('-date_created',), 'verbose_name': 'Car Category', 'verbose_name_plural': 'Car Categories'},
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='class_name',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Truck', 'Truck'), ('SUV', 'SUV'), ('Van', 'Van')], default='Standard', max_length=50),
        ),
    ]
