# Generated by Django 4.1.5 on 2023-01-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_name', models.CharField(max_length=30)),
                ('renter_phone_number', models.CharField(max_length=13)),
                ('renter_email', models.CharField(max_length=50)),
                ('renter_dob', models.DateField()),
                ('renter_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('renter_country', models.CharField(max_length=100)),
                ('renter_address', models.TextField(max_length=100)),
                ('total_days', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('pickup_date', models.DateTimeField()),
                ('dropoff_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
