# Generated by Django 4.0.2 on 2023-03-14 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_name', models.CharField(max_length=30)),
                ('renter_title', models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Miss', 'Miss')], max_length=6)),
                ('renter_phone_number', models.CharField(max_length=13)),
                ('renter_email', models.CharField(max_length=50)),
                ('renter_country', models.CharField(max_length=100)),
                ('renter_city', models.CharField(max_length=50)),
                ('renter_address', models.TextField(max_length=100)),
                ('total_days', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Current', 'Current'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=9)),
                ('approved', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('request_declined', models.BooleanField(default=False)),
                ('pickup_date', models.DateTimeField()),
                ('dropoff_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('booked_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carcategory')),
                ('dropoff_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff', to='cars.location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='cars.location')),
            ],
        ),
    ]
