# Generated by Django 4.0.2 on 2023-02-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='renter_city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='canceled',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Current', 'Current'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=9),
        ),
    ]
