# Generated by Django 4.0.2 on 2023-02-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_renter_city_alter_booking_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Current', 'Current'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=9),
        ),
    ]
