# Generated by Django 4.0.2 on 2023-02-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_request_canceled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='request_canceled',
            new_name='request_declined',
        ),
    ]
