# Generated by Django 4.0.2 on 2023-02-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carcategory_remove_car_owner_and_more'),
        ('bookings', '0006_rename_request_canceled_booking_request_declined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carcategory'),
        ),
    ]
