# Generated by Django 4.0.2 on 2023-02-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_booked_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='renter_title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Miss', 'Miss')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
