# Generated by Django 4.0.2 on 2023-02-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_renter_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='renter_dob',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='renter_gender',
        ),
    ]
